Datos de pueba

INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (1,"elit,","vulputate,","4","1"),(2,"ultrices","leo","3","0"),(3,"nec","nibh.","2","1"),(4,"Mauris","urna.","3","0"),(5,"convallis","erat","5","1"),(6,"et","Lorem","3","1"),(7,"consectetuer,","quis","2","0"),(8,"Phasellus","massa","5","1"),(9,"semper","vehicula","1","0"),(10,"sed","euismod","2","0");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (11,"feugiat","egestas.","4","1"),(12,"lacus.","dui","1","1"),(13,"varius.","sagittis","2","1"),(14,"eros","risus.","5","1"),(15,"dictum","nibh.","4","0"),(16,"vulputate,","mi","4","0"),(17,"Donec","diam","5","0"),(18,"sagittis","convallis","2","0"),(19,"primis","luctus.","4","1"),(20,"scelerisque","Morbi","3","1");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (21,"Vestibulum","eget","3","0"),(22,"consectetuer","ornare,","1","0"),(23,"eleifend,","cursus.","5","0"),(24,"Suspendisse","consectetuer","3","1"),(25,"sem","eu","1","0"),(26,"quis,","Aliquam","2","1"),(27,"varius","sapien.","4","1"),(28,"nulla","dolor.","4","1"),(29,"magna.","ligula","1","0"),(30,"aliquet.","eget","1","1");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (31,"Aliquam","neque","4","0"),(32,"parturient","tincidunt","2","0"),(33,"a,","orci","4","1"),(34,"adipiscing.","libero.","1","0"),(35,"id","commodo","2","0"),(36,"amet,","sit","2","1"),(37,"tempor","amet","5","1"),(38,"ac","a,","3","0"),(39,"a,","et,","5","1"),(40,"non","Duis","1","0");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (41,"feugiat.","mauris","4","0"),(42,"mi","dictum","3","1"),(43,"non","sociis","3","1"),(44,"libero.","consequat","2","0"),(45,"Donec","gravida","4","1"),(46,"placerat","pellentesque","5","1"),(47,"consectetuer","cubilia","5","0"),(48,"sed,","malesuada","2","1"),(49,"tincidunt,","vitae","2","1"),(50,"magna.","et","5","1");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (51,"arcu.","elit.","2","1"),(52,"id,","mauris","1","1"),(53,"cursus.","varius","3","1"),(54,"sem","Donec","4","1"),(55,"laoreet","ante,","3","1"),(56,"massa.","diam","5","0"),(57,"consectetuer","auctor","1","0"),(58,"faucibus","Proin","4","0"),(59,"tristique","et","5","0"),(60,"ornare","gravida","4","1");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (61,"felis.","egestas","2","0"),(62,"ipsum","Sed","2","0"),(63,"neque.","enim","3","0"),(64,"facilisis,","tortor","4","1"),(65,"eleifend","eros.","1","0"),(66,"turpis","Cras","1","0"),(67,"ultrices,","non,","3","1"),(68,"ultricies","arcu","5","1"),(69,"sodales","sem","3","1"),(70,"lorem","Phasellus","4","1");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (71,"Sed","massa.","4","1"),(72,"eu,","risus","3","1"),(73,"dolor.","at,","3","0"),(74,"et","cursus","4","0"),(75,"Cras","consequat","1","1"),(76,"nisi.","sagittis","4","1"),(77,"tellus.","sapien,","2","0"),(78,"neque","in","1","1"),(79,"interdum.","ante.","4","1"),(80,"augue","Donec","1","0");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (81,"erat","molestie","5","0"),(82,"et","felis","2","0"),(83,"Donec","hendrerit.","1","0"),(84,"sagittis","Sed","3","0"),(85,"pellentesque,","Sed","1","1"),(86,"In","pharetra.","3","0"),(87,"in","quis","4","0"),(88,"Donec","dolor","5","1"),(89,"magna.","Nullam","2","1"),(90,"libero","congue","4","0");
INSERT INTO `favooru_accesos` (`accesos_id`,`accesos_usuario`,`accesos_pass`,`accesos_producto_id`,`accesos_disponibilidad`) VALUES (91,"mattis","luctus","4","1"),(92,"semper","aliquet","4","0"),(93,"Praesent","tristique","4","0"),(94,"risus.","orci,","5","1"),(95,"venenatis","risus.","4","0"),(96,"elit,","at,","1","1"),(97,"diam","vel,","1","0"),(98,"Phasellus","risus","3","1"),(99,"tempor,","id","5","0"),(100,"cursus.","vestibulum.","4","1");